# Generated by Django 5.2.4 on 2025-08-21 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('accommodation', 'Accommodation'), ('transport', 'Transport'), ('meals', 'Meals'), ('medical', 'Medical & Insurance'), ('experience', 'Experience')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Add-on Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pricing_type', models.CharField(choices=[('per_person', 'Per Person'), ('per_group', 'Per Group'), ('fixed', 'Fixed Price')], default='per_person', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default/included option?')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='destinations.addoncategory')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_options', to='destinations.destination')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'destination', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.CharField(blank=True, help_text="e.g., '2 hours', 'Half day'", max_length=50)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_addons', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('destination', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.addonoption')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='destinations.booking')),
                ('experience_addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.experienceaddon')),
            ],
            options={
                'unique_together': {('booking', 'addon_option'), ('booking', 'experience_addon')},
            },
        ),
    ]
