# Generated by Django 5.0.1 on 2025-12-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_addoncategory_addonoption_experienceaddon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='end_date',
            field=models.DateField(blank=True, help_text='Tour end date', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tour start date', null=True),
        ),
    ]
