# Generated by Django 5.2.4 on 2025-10-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_add_booking_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='destination_booking_ecd8ee_idx',
            old_name='destinations_booking_type_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='destination_booking_3c8c88_idx',
            old_name='destinations_booking_type_status_idx',
        ),
    ]
