# Generated by Django 5.2.5 on 2025-12-02 01:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_end_date_destination_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this group size range', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Effective price per person (for display)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='destinations.destination')),
            ],
            options={
                'ordering': ['destination', 'min_people'],
                'indexes': [models.Index(fields=['destination', 'min_people', 'max_people'], name='destination_destina_c9891e_idx')],
                'unique_together': {('destination', 'min_people', 'max_people')},
            },
        ),
    ]
