# Generated by Django 5.2.4 on 2025-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_rename_destinations_booking_type_idx_destination_booking_ecd8ee_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/gallery/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
