# Generated by Django 5.2.4 on 2025-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_destinationimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.URLField(blank=True, help_text='Image URL', max_length=500, null=True),
        ),
    ]
