# Generated by Django 5.2.4 on 2025-10-16 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_destination_image_alter_destinationimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.PositiveIntegerField(help_text='Minimum number of people for this price', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_people', models.PositiveIntegerField(help_text='Maximum number of people for this price (leave blank for unlimited)', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price per person for this group size', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='destinations.destination')),
            ],
            options={
                'ordering': ['min_people'],
                'indexes': [models.Index(fields=['destination', 'min_people', 'max_people'], name='destination_destina_c9891e_idx')],
                'unique_together': {('destination', 'min_people')},
            },
        ),
    ]
