# Generated by Django 5.2.4 on 2025-10-16 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_pricingtier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingtier',
            name='max_people',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of people for this price (leave blank for unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
