# Generated by Django 5.2.4 on 2025-10-16 02:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_image_alter_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('transport', 'Transport'), ('meals', 'Meals'), ('medical', 'Medical & Insurance'), ('experience', 'Experience'), ('equipment', 'Equipment'), ('service', 'Service')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Add-On Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('addon_type', models.CharField(choices=[('single', 'Single Selection'), ('multiple', 'Multiple Options'), ('checkbox', 'Optional Add-on')], default='checkbox', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('per_person', 'Per Person'), ('per_group', 'Per Group'), ('percentage', 'Percentage of Base Price')], default='fixed', max_length=20)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('is_required', models.BooleanField(default=False, help_text='If true, this add-on must be selected')),
                ('is_default', models.BooleanField(default=False, help_text='If true, this add-on is selected by default')),
                ('max_quantity', models.PositiveIntegerField(default=1, help_text='Maximum quantity per booking')),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features/benefits')),
                ('terms_conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='available_addons', to='tickets.ticketcategory')),
                ('applicable_tickets', models.ManyToManyField(blank=True, related_name='available_addons', to='tickets.ticket')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='tickets.addoncategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddOnOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tickets.addon')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(help_text='Reference to the main booking', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.addon')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.addonoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['category', 'is_active'], name='tickets_add_categor_151d03_idx'),
        ),
        migrations.AddIndex(
            model_name='addon',
            index=models.Index(fields=['is_active', 'order'], name='tickets_add_is_acti_4ea594_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addonoption',
            unique_together={('addon', 'name')},
        ),
        migrations.AddIndex(
            model_name='bookingaddon',
            index=models.Index(fields=['booking_reference'], name='tickets_boo_booking_6001e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingaddon',
            index=models.Index(fields=['customer_email'], name='tickets_boo_custome_bcaca3_idx'),
        ),
    ]
