# Generated by Django 5.2.5 on 2025-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='configuration',
            field=models.JSONField(default=dict, help_text='Provider-specific configuration'),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
