# Generated by Django 5.2.4 on 2025-08-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.RunSQL(
            # Remove the foreign key constraint to the non-existent bookings_tourbooking table
            sql="""
            -- Create a new payments table without the bookings foreign key
            CREATE TABLE "payments_payment_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
                "payment_id" char(32) NOT NULL UNIQUE, 
                "reference" varchar(50) NOT NULL UNIQUE, 
                "amount" decimal NOT NULL, 
                "currency" varchar(3) NOT NULL, 
                "payment_method" varchar(20) NOT NULL, 
                "phone_number" varchar(15) NOT NULL, 
                "status" varchar(20) NOT NULL, 
                "external_reference" varchar(100) NOT NULL, 
                "created_at" datetime NOT NULL, 
                "updated_at" datetime NOT NULL, 
                "processed_at" datetime NULL, 
                "description" text NOT NULL, 
                "metadata" text NOT NULL CHECK ((JSON_VALID("metadata") OR "metadata" IS NULL)), 
                "user_id" bigint NULL REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED, 
                "provider_id" bigint NULL REFERENCES "payments_paymentprovider" ("id") DEFERRABLE INITIALLY DEFERRED, 
                "booking_id" bigint NULL REFERENCES "destinations_booking" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            
            -- Copy data from old table to new table
            INSERT INTO "payments_payment_new" 
            SELECT "id", "payment_id", "reference", "amount", "currency", "payment_method", 
                   "phone_number", "status", "external_reference", "created_at", "updated_at", 
                   "processed_at", "description", "metadata", "user_id", "provider_id", NULL
            FROM "payments_payment";
            
            -- Drop old table and rename new table
            DROP TABLE "payments_payment";
            ALTER TABLE "payments_payment_new" RENAME TO "payments_payment";
            
            -- Recreate indexes
            CREATE INDEX "payments_payment_user_id_status_idx" ON "payments_payment" ("user_id", "status");
            CREATE INDEX "payments_payment_status_created_at_idx" ON "payments_payment" ("status", "created_at");
            CREATE INDEX "payments_payment_reference_idx" ON "payments_payment" ("reference");
            CREATE INDEX "payments_payment_external_reference_idx" ON "payments_payment" ("external_reference");
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
