# Generated by Django 5.0.1 on 2025-12-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20250820_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('paystack', 'Paystack')], default='momo', max_length=20),
        ),
    ]
