# Generated by Django 5.2.4 on 2025-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.URLField(help_text='Image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Thumbnail URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='thumbnail',
            field=models.URLField(help_text='Video thumbnail URL', max_length=500),
        ),
    ]
