# Generated by Django 5.2.4 on 2025-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_image_gallery_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
