# Generated by Django 5.2.4 on 2025-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_add_video_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (MP4, WebM, etc.) - alternative to file upload', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (optional if using video URL)', null=True, upload_to='gallery/videos/%Y/%m/'),
        ),
    ]
